/**
 * Writes a commands manifest next to the built commands (Console's
 * `IndexGenerator`).
 *
 * What it buys: listing the commands, or checking that one exists, without
 * importing a single command module. Scanning a directory means importing every
 * file in it — the manifest replaces that with one JSON read.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import { FsLoader } from './loaders.js'
import type { SerializedCommand } from './types.js'

/** What `commands.json` holds. `version` is there to survive a format change. */
export interface CommandsManifest {
  version: 1
  commands: SerializedCommand[]
}

export class IndexGenerator {
  readonly #directory: URL

  constructor(commandsDirectory: string | URL) {
    this.#directory =
      typeof commandsDirectory === 'string'
        ? pathToFileURL(`${commandsDirectory}/`)
        : commandsDirectory
  }

  /**
   * Write `commands.json` and the `main.js` / `main.d.ts` loader beside the
   * commands. Returns the manifest, so a caller can report what it indexed.
   */
  async generate(): Promise<CommandsManifest> {
    const commands = await new FsLoader(this.#directory).getMetaData()
    const manifest: CommandsManifest = { version: 1, commands }

    await mkdir(this.#directory, { recursive: true })
    await writeFile(new URL('commands.json', this.#directory), JSON.stringify(manifest, null, 2))
    await writeFile(new URL('main.js', this.#directory), LOADER)
    await writeFile(new URL('main.d.ts', this.#directory), LOADER_TYPES)

    return manifest
  }
}

/**
 * The generated loader. It satisfies `CommandLoader` structurally, so the
 * kernel takes it as-is: `kernel.addLoader(await import('./commands/main.js'))`.
 */
const LOADER = `import { readFile } from 'node:fs/promises'

/** Generated by Ream's IndexGenerator — do not edit. */
let manifest

export async function getMetaData() {
  if (manifest === undefined) {
    const contents = await readFile(new URL('./commands.json', import.meta.url), 'utf-8')
    manifest = JSON.parse(contents).commands
  }
  return manifest
}

export async function getCommand(metadata) {
  const commands = await getMetaData()
  const command = commands.find((entry) => entry.commandName === metadata.commandName)
  if (command === undefined) return null

  const imported = await import(new URL(command.filePath, import.meta.url).href)
  return imported.default ?? null
}
`

const LOADER_TYPES = `import type { CommandClass, SerializedCommand } from '@c9up/ream'

export declare function getMetaData(): Promise<SerializedCommand[]>
export declare function getCommand(metadata: SerializedCommand): Promise<CommandClass | null>
`
